---
title: "DAILY REPORT ON COVID 19"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
source("Rating.R")
library(ggplot2)
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Overall COVID case per 100k population

```{r}
cond <- WHO_data$Name %in% c("Global", "United States of America", "India", "The United Kingdom", "Germany", "Brazil")
df <- WHO_data[cond, ]
df$Name <- as.factor(df$Name)

ggplot(data = df, aes(x = Name, y = Cases...newly.reported.in.last.7.days.per.100000.population)) + 
  geom_bar(stat = "identity", fill = "steelblue") + 
  theme_minimal() + 
  labs(x = "", y = "Number of new cases", title = "New cases per 100,000 population in the last 7 days") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 20, vjust = 0.5, hjust=1))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
data("USArrests", package = "datasets")
data("usgeojson")

USArrests <- USArrests %>%
  mutate(state = rownames(.))

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()

highchart() %>%
  hc_add_series_map(usgeojson, USArrests, name = "Sales",
                    value = "Murder", joinBy = c("woename", "state"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```

### Chart C

```{r}

```

